server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sbb_2nd?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: ysh
    password: ysh123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


            <!--jpa? mysql?? ??? ??? ??? ????? ??? ?? ???? ???? jpa??? ????? mysql? ????? ???? ? ???? ??? ???? ?? ??? ?? -->
            <!-- mysql? ???? ?? ?? ???? ?? -->